server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9001/
          predicates:
            - Path=/users/**
        - id: FAVORITE-CITIES-SERVICE
          uri: http://localhost:9002/
          predicates:
            - Path=/**
        - id: FAVORITE-SERVICE
          uri: http://localhost:9003/
          predicates:
            - Path=/favorite/**
